version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rails
    versions:
    - "> 4.2.11.1"
  - dependency-name: sqlite3
    versions:
    - ">= 1.4.a, < 1.5"
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.8.1
    - 1.9.1
  - dependency-name: timecop
    versions:
    - 0.9.2
    - 0.9.3
  - dependency-name: recaptcha
    versions:
    - 5.6.0
  - dependency-name: rspec-rails
    versions:
    - 4.0.0
