# Site's name:
name: 'Volunteer Odyssey'

# Site's tagline:
tagline: "Find volunteer opportunities in Memphis, TN."

# Site's URL with trailing slash:
url: 'http://www.volunteeerodyssey.org/'

# Default timezone, run "rake -D time" for information on how to display known timezones:
timezone: 'Central Time (US & Canada)'

# Precompile additional theme assets (theme.js, theme.css, and images already included):
precompile_assets:
  - 'mobile.css'
  - 'print.css'

# Map to display on /venues page:
venues_map_options:
  # Zoom magnification level:
  zoom: 12
  # Center of the map, in latitude and longitude.
  # If no center is specified, the map will zoom to fit all markers.
  center: [35.1174, 89.9711]
