require "calagator/engine"

require "formtastic"
require "rails_autolink"
require "rails-observers"
require "nokogiri"
require "columnize"
require "geokit"
require "htmlentities"
require "paper_trail"
require "ri_cal"
require "will_paginate"
require "will_paginate/array"
require "rest-client"
require "loofah"
require "loofah-activerecord"
require "bluecloth"
require "formtastic"
require "acts-as-taggable-on"
require "jquery-rails"
require "jquery-ui-rails"
require "font-awesome-rails"
require "paper_trail_manager"
require "utf8-cleaner"
require "sunspot_rails"
require "sunspot_solr"
require "lucene_query"

module Calagator
end
