# PostgreSQL.
#
# Install the ruby-postgres driver:
#   gem install pg
# On Mac OS X:
#   gem install pg -- --include=/usr/local/pgsql

common: &common
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USER'] %>
  password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432
  #
  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

development:
  database: calagator_dev
  << : *common

preview:
  database: calagator_dev
  << : *common

test:
  database: calagator_test
  << : *common

production:
  database: calagator_prod
  << : *common
