# MySQL.  Versions 5.x are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.

common: &common
  adapter: mysql2
  encoding: utf8
  socket: <%= `mysql_config --socket`.chomp %>
  username: <%= ENV['DBUSER_MYSQL'] || ENV['DBUSER'] || ENV['USER'] %>
  password:

development:
  database: calagator_dev
  << : *common

preview:
  database: calagator_dev
  << : *common

test:
  database: calagator_test
  << : *common

production:
  database: calagator_prod
  << : *common
