# Site's name:
name: 'Toledo Tech Events'

# Site's tagline:
tagline: "The Toledo Region's Tech Calendar"

# Site's URL with trailing slash:
url: 'http://tol-calagator.org/'

# Default timezone, run "rake -D time" for information on how to display known timezones:
timezone: 'Eastern Time (US & Canada)'

# Google map to display on /venues page:
venues_google_map_options:
  # Zoom magnification level:
  zoom: 10
  # Center of the map, in latitude and longitude:
  center: [41.651126,-83.536844]

# Array of tag names to exclude from tag cloud:
tagcloud_exclusions:
  - ostartupskey
  - tvg
